language: go
go: 
  - 1.4
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
addons:
  code_climate:
    repo_token: f67745505f55668c4284bb600fc3710c4a7f05ed75ba8e9ebd313cd3097b686b
after_script:
  - codeclimate < lcov.info